# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6TvzCdbAPdZOgqgn-vrSJdVGJCyOKSV
"""

a=float(input("enter the value of a:"))
    b=float(input("enter the value of b:"))
    c=float(input("enter the value of c:"))
    x=float(input("enter the value of x:"))




    y = a*(x*x)+b*x+c;
    print("for the values:a",a,"b",b,"c",c,"y is:",y)