# -*- coding: utf-8 -*-
"""v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6TvzCdbAPdZOgqgn-vrSJdVGJCyOKSV
"""

filename = "/content/sample_data/data.txt"

try:
    with open(filename, 'r') as file:

        line = file.readline().strip()
        a, b, c, x = map(float, line.split(','))
except FileNotFoundError:
    print(f"Error: {filename} not found.")
    exit()
except ValueError:
    print("Error: Ensure the file contains valid numerical values in the format a,b,c,x.")
    exit()

y = a * (x**2) + b * x + c


print(f"For the values a = {a}, b = {b}, c = {c}, x = {x}, the value of y is: {y}")