# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6TvzCdbAPdZOgqgn-vrSJdVGJCyOKSV
"""

a=5
    b=4
    c=6
    x=4.5
    y=0



    y = a*(x*x)+b*x+c;
    print("for the values:a",a,"b",b,"c",c,"y is:",y)